-- Add new columns to Payments table
ALTER TABLE Payments
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS fraud_status VARCHAR(20),
ADD COLUMN IF NOT EXISTS bank VARCHAR(50),
ADD COLUMN IF NOT EXISTS va_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS three_ds BOOLEAN DEFAULT FALSE;
